### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by SebastianoLpwave** [dustin-johnson/timezonemap#14]
Hi, 
I need to initialize the library using TimeZoneMap.forEverywhere() but i recieve out of memory error .
I tried to initialize it for a specific region and it doesn't happen.

Error log: 
![oomException](https://github.com/dustin-johnson/timezonemap/assets/35693239/f55895ff-c0cf-4414-a75d-86a9348694f6)

Below is how I initialize the library in the Application.class

>     public static class InitTimeZone {
>         public static void init() {
>             //if (timeZoneMap == null) {
>                 Thread thread = new Thread(() -> {
>                     //timeZoneMap = TimeZoneMap.forRegion(43.5, 8.0, 53.00, 26.0);;
>                     timeZoneMap = TimeZoneMap.forEverywhere();
>                     Logger.log(Level.INFO, "timezone map init done");
>                 });
>                 thread.start();
>             //}
>         }
>     }

Am I doing something wrong?
Thanks

**Comment by dustin-johnson** [comment]
Hi @SebastianoLpwave, from the stack trace it appears you are operating with extremely constrained memory limits. If you try to use `forRegion` for an extremely small region, say less than a degree for both Lat and Lon, does it still run out of memory?

**Comment by SebastianoLpwave** [comment]
> Hi @SebastianoLpwave, from the stack trace it appears you are operating with extremely constrained memory limits. If you try to use `forRegion` for an extremely small region, say less than a degree for both Lat and Lon, does it still run out of memory?

Hi,
with a small region the problem does not occur. Does this mean that I have to initialize the library dynamically every time I leave the region used to init the library? Example I start from Italy and then at a certain point the GPS coordinates do not fall within the Italian region. At this point I have to initialize the library again with a new region!

Thanks

**Comment by dustin-johnson** [comment]
Yep, it means that you'll want to grab a new region when your location moves out of your existing region. The API was designed to operate this way on memory constrained devices, such as phones.
