### ISSUE TITLE
Crash occured at TimeZoneMap.forEverywhere()

### ISSUE THREAD

**Issue by NawshadHamid** [dustin-johnson/timezonemap#6]
2021-03-01 15:54:07.998 19080-19080/com.example E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example-tKd8zN8SGYlg-8pgPZbq_g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example-tKd8zN8SGYlg-8pgPZbq_g==/lib/arm, /system/lib]]] couldn't find "libzstd-jni.so"
    Unsupported OS/arch, cannot find /linux/armv8l/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)

**Comment by dustin-johnson** [comment]
It looks like the zstd library is missing. Did you import it as such:

```
implementation('us.dustinj.timezonemap:timezonemap:4.0`) {
    // Exclude standard compression library
    exclude group: 'com.github.luben', module: 'zstd-jni'
}
// Import aar for native component compilation
implementation 'com.github.luben:zstd-jni:1.4.4-3@aar'
```
