### ISSUE TITLE
TimeZoneMap.forEverywhere() blocks with org.apache.commons:commons-compress:1.20

### ISSUE THREAD

**Issue by epgoranova** [dustin-johnson/timezonemap#9]
I'm using version 4.0  and it works with `org.apache.commons:commons-compress:1.19`.

A different dependency in my project uses `org.apache.commons:commons-compress:1.20`. It seems that this newer version causes `TimeZoneMap.forEverywhere()` to block indefinitely and the invocation never returns.

**Comment by dustin-johnson** [comment]
Thanks for the heads up! I believe I've found and fixed the issue. I've taken this opportunity to update all the dependencies to the latest and update the internal maps as well. Version 4.1 is currently building but should be available on maven central soon.

**Comment by dustin-johnson** [comment]
Update: I had quite a few issues getting the library pushed to maven central. The version with this fix is 4.5.

**Comment by epgoranova** [comment]
All seems good after updating to 4.5. Thank you for the prompt response!
